### PR TITLE
Add postcss-loader and autoprefixer module

### PR DESCRIPTION
**Pull request by AlexImb**
Add automated vendor prefixes to CSS rules for the browsers specified in the .browserlistrc file.

Tried this as a fix for #107 but fixed it manually for that particular instance in #112

Bundle size increase for the current .browserlistrc is about 8%, for `last 10 versions` about  10%.

### CODE REVIEW

**Comment by thlassche** [comment]
@AlexImb I think this is a good idea to increase cross-vendor and cross-browser compatibility. What is the absolute increase in bundle size (instead of the percentual increase)?

**Comment by AlexImb** [comment]
The current bundle is 386KB uncompressed so it'll be about 40KB more which I think is reasonable even for 3G speeds.

**Comment by thlassche** [comment]
Ok, fine by me (after it's carefully tested in Cypress / Browserstrack)

**Comment by thlassche** [comment]
@AlexImb can you rebase this one?

**Comment by AlexImb** [comment]
Cherrypicked the relevant commits, squashed and added them on master.

**Pull request closed without merging**
