### PR TITLE
Frank/tank gauges alignment

### PR DESCRIPTION
**Pull request by fwaalkens**
Fixed multiple issues regarding the tanks UI.
- Horizontal view flickering
- Alignment on smaller views
- Added translations for tank overview
- Minor semantic fixes

image

image

image

### CODE REVIEW

**Comment by martinbosma** [comment]
In below screenshots there appears to be enough width, yet the tank name is truncated to only a few characters. Can we improve this? Make the gauge less wide and add more room for the name?

Simulation: `./run.sh -s s`

1800x900:
Screen Shot 2024-02-26 at 14 39 45

1500x500:
Screen Shot 2024-02-26 at 14 44 59

800x900, Text gets truncated, while there is still space:
Screen Shot 2024-02-26 at 14 42 47

**Comment by martinbosma** [comment]
Much better, although sometimes the text still get truncated while there is enough space.

1800x900:
Screen Shot 2024-02-26 at 16 54 27

**Comment by fwaalkens** [comment]
Tested on multiple mfd's:

image
image
image
image

**Review by martinbosma — APPROVED** [review]
LGTM

**Pull request merged**
