### PR TITLE
added new component: FpGen

### PR DESCRIPTION
**Pull request by khasenklever**
New component to visualize and control a Fischer Panda generator set.
The component consists of:
* state
* AC values (voltage, currenr, power, frequency)
* starter battery voltage
* temperatures (coolant, winding, exhaust)
* manual on/off-request buttons

### CODE REVIEW

**Comment by jabba80** [comment]
fpgen

**Comment by jabba80** [comment]
fpgen_3ph

**Comment by martinbosma** [comment]
Hi, @khasenklever & @jabba80. Thanks for the PR, a pleasant surprise! 
Adding a FP generator component seems like a nice addition to me.
We need some time to review and come back to this.

**Comment by khasenklever** [comment]
Hi, 
I recently modified this code a bit, because it looked a bit wrong on our HDS7 live (we got just today).
Screenshot_2020-01-10_23 42 26

My modification was to use ListView instead of HeaderView: khasenklever/venus-html5-app@b0a5a67d46f535edeb2e5018747891f5399376a7 .  
Now it looks like this:
Screenshot_2020-01-10_23 46 25

Any hint why the Title and the Subtitle have this offset to the right?
And any idea, why it is always directly stopping the gen again after pressing "on"?

**Comment by khasenklever** [comment]
@martinbosma just fixed the title-offset on Lowrance MFD. Seems as if somenthing goes wrong when the Lowrance Browser scales the svg.

**Comment by martinbosma** [comment]
> @martinbosma just fixed the title-offset on Lowrance MFD. Seems as if somenthing goes wrong when the Lowrance Browser scales the svg.

Ok, thanks. @AlexImb & @thlassche

**Comment by AlexImb** [comment]
Rebased onto the latest master. 
Closing in favour of #131.

**Pull request closed without merging**
